augustine_platform_home:
    path:      /index
    defaults:  { _controller: AugustinePlatformBundle:Advert:index }

augustine_platform_history:
    path:      /historique/{page}
    defaults:  { _controller: AugustinePlatformBundle:Advert:history, page : 2 }

augustine_platform_sponsor:
    path: /sponsors
    defaults: { _controller: AugustinePlatformBundle:Sponsor:index }
    
augustine_platform_ajouter:
    path:      /ajouter
    defaults:  { _controller: AugustinePlatformBundle:Advert:ajouter }
    
augustine_platform_etablissements:
    path:      /etablissements
    defaults:  { _controller: AugustinePlatformBundle:Advert:etablissements }
    
augustine_platform_voir:
    path:      /voir/{id}
    defaults:  { _controller: AugustinePlatformBundle:Advert:voir }
    requirements:
        id: \d+
        
augustine_platform_editer:
    path:      /editer/{id}
    defaults:  { _controller: AugustinePlatformBundle:Advert:editer }
    requirements:
        id: \d+