augustine_platform_home:
    path:      /index/{page}
    defaults:  { _controller: AugustinePlatformBundle:Advert:index, page : 1 }

augustine_platform_history:
    path:      /historique/{page}
    defaults:  { _controller: AugustinePlatformBundle:Advert:history, page : 2 }

augustine_platform_sponsor:
    path: /sponsors
    defaults: { _controller: AugustinePlatformBundle:Sponsor:index }