<?php

namespace Augustine\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActuRepository extends EntityRepository
{
}
